STRAVA_CLIENT_ID: '44973'
STRAVA_CLIENT_SECRET: '2ed9b35113cc71c7b53460dedae05ef2b142133d'
LINE_CHANNEL_ACCESS_TOKEN: 'z24FeCXZX2E3bx/BfeGxRttiRMwwkutV1+Q4Sr6w8UInBLjCpmcVNmewMDLLAahezZNJQD73ogwgB9VEmVndAKNl8fzXFyRSLGj3gMubocMVbCnq8MGgM4VMnQ5Zd4hUHkf/io0YZdReOvyALa3RAwdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET: '5796fa888d9fd7b505ac780ecf27c4ae'
ZWIFT_ACTIVITY_DIR: 'C:\Users\USER\Documents\Zwift\Activities'
GMAIL_USER_ID: 'huaming.huang.tw@gmail.com'
GMAIL_PASSWORD: 'eomzmbjezezpcsnv'